### ISSUE TITLE
Launch Notitificare callback is triggered on a background thread

### ISSUE THREAD

**Issue by JGanol** [Notificare/notificare-sdk-ios#13]
Hi guys,

I am experiencing issues with `func notificare(_ notificare: Notificare, onReady application: NotificareApplication)` from NotificareDelegate being called on a background thread. I suppose that if I initiate setup on one thread I am notified about changes on the same thread. So if I `launch()` Notificare on the main thread, I get it back the same way. Maybe it can be improved anyhow? I am on version 3.1.0.

Best regards.

**Comment by hpinhal** [comment]
Hi @JGanol, 

Since the `launch()` method is not synchronous with any of the delegate method events it produces, ensuring the delegates are called on the same thread might prove difficult. However, we can ensure they are always called on the **main thread**.
Would this work for you?

Thanks for your feedback.

**Comment by JGanol** [comment]
Hi hpinhal,
As main thread is usually the most used, that can be a better solution, indeed. At least the most preferable to expect.  :)
Kind regards.

**Comment by hpinhal** [comment]
Hi @JGanol,

This feature is shipping in today's release. 🚀 
Version 3.2.0
